src/android/urls.py
from django.urls import path

from android.views import (
	android_screen_view,
	detail_blog_view,

)

app_name = 'android'

urlpatterns = [
    path('', android_screen_view, name="android"),
    path('<slug>/', detail_blog_view, name="detail"),
 ]

src/blog/urls.py
from django.urls import path

from blog.views import (
	detail_blog_view,

)

app_name = 'blog'

urlpatterns = [
    path('<slug>/', detail_blog_view, name="detail"),
 ]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from personal.views import (
	home_screen_view,

)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
)

from courses.views import (
    courses_screen_view,

    )


urlpatterns = [
	
    path('', home_screen_view, name="home"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('courses/', courses_screen_view, name="courses"),
    path('android/', include('android.urls', 'android')),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: #f2f2f2;
	}
</style>

src/templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->
<br>
<div class="d-flex flex-row align-items-center footer  bg-white border-top shadow-lg">
	<p class="m-auto">CodingWithMitch Blog Course | 2019</p>
</div>
<!-- End Footer -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/templates/snippets/header.html
{% load static %}

<style type="text/css">




</style>
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-white border-bottom shadow-sm">

	<a class="navbar-brand" href="{% url 'home' %}" style="color: black;" >
   	    <img  src="{% static 'app.png' %}" width="30" height="30" class="mr-2 d-inline-block align-top" alt="prefectCoding logo">
    PrefectCoding
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

    <div class="navbar-nav mr-auto">

      {% if request.user.is_authenticated %}

   		<a class="nav-item nav-link p-2 text-dark" href="{% url 'android:android' %}">Java</a>
   		<a class="nav-item nav-link p-2 text-dark" href="{% url 'android:android' %}">Android</a>
   		<a class="nav-item nav-link p-2 text-dark" href="{% url 'home' %}">MCQ</a> 
		  <a class="nav-item nav-link p-2 text-dark" href="{% url 'account' %}">Account</a> 
		{# <a class="btn btn-outline-p7rimary" href="{% url 'logout' %}">Logout</a> #}

	{% else %}

	   <a class="nav-item nav-link p-2 text-dark" href="{% url 'home' %}">Home</a> 
	   <a class="nav-item nav-link p-2 text-dark" href="{% url 'android:android' %}">Java</a>
   		<a class="nav-item nav-link p-2 text-dark" href="{% url 'android' %}">Android</a>
   		<a class="nav-item nav-link p-2 text-dark" href="{% url 'home' %}">MCQ</a> 
	   {# <a class="p-2 text-dark btn btn-outline-primary" href="{% url 'register' %}">Register</a>   #}
     
	{% endif %}



    </div>

    <form method="get" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2"  type="text" name="q" id="id_q" placeholder="Search...">
    </form>
 
	 {% if request.user.is_authenticated %}
			<a class="nav-item nav-link btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
	{% else %}
			<a class="mr-lg-2 nav-item nav-link btn btn-outline-primary" href="{% url 'login' %}">Login</a></p>
			<a class="nav-item nav-link btn btn-outline-primary" href="{% url 'register' %}">Register</a>  
	{% endif %}

      
  </div>
</nav>


<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>