src/android/urls.py
from django.urls import path

from android.views import (
	android_screen_view,
	detail_blog_view,

)

app_name = 'android'

urlpatterns = [
    path('', android_screen_view, name="android"),
    path('<slug>/', detail_blog_view, name="detail"),
 ]

src/blog/urls.py
from django.urls import path

from blog.views import (
	detail_blog_view,

)

app_name = 'blog'

urlpatterns = [
    path('<slug>/', detail_blog_view, name="detail"),
 ]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from personal.views import (
	home_screen_view,

)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
)

from courses.views import (
    courses_screen_view,

    )


urlpatterns = [
	
    path('', home_screen_view, name="home"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('courses/', courses_screen_view, name="courses"),
    path('android/', include('android.urls', 'android')),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/android/models.py
from django.db import models

from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver

def upload_location(instance, filename):
	file_path = 'android/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path


class AndroidPost(models.Model):
	title 					= models.CharField(max_length=50, null=False, blank=False)
	body 					= models.TextField(max_length=50000, null=False, blank=False)
	image		 			= models.ImageField(upload_to=upload_location, null=True, blank=True)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 					= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title

@receiver(post_delete, sender=AndroidPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=AndroidPost)

src/android/views.py
from django.shortcuts import render, redirect, get_object_or_404
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from android.models import AndroidPost

from django.db.models import Q

BLOG_POSTS_PER_PAGE = 9

def android_screen_view(request, *args, **kwargs):
	
	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
	


	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "android/home.html", context)




def detail_blog_view(request, slug):

	context = {}
	blog_posts_list = sorted(AndroidPost.objects.all(), key=attrgetter('date_updated'), reverse=False)
	blog_post = get_object_or_404(AndroidPost, slug=slug)
	context['blog_post'] = blog_post
	context['blog_posts_list'] = blog_posts_list

	return render(request, 'android/detail_blog.html', context)



def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ")
	for q in queries:
		posts = AndroidPost.objects.filter(
			Q(title__contains=q)|
			Q(body__icontains=q)
			).distinct()
		for post in posts:
			queryset.append(post)

	# create unique set and then convert to list
	return list(set(queryset)) 

src/android/templates/android/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

src/android/templates/android/snippets/blog_post_snippet.html
<style type="text/css">

</style>

{% if blog_post %}

        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          	<a href="{% url 'android:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
            <div class="card-body">
             <a href="">
					<h4 class="card-title">{{blog_post.title}}</h4>
				</a>
				<p class="card-text">{{blog_post.body|safe|truncatechars:180}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">{{blog_post.date_updated}}</small>
              </div>
            </div>
          </div>
        </div>


{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}